
HT_flag = False # to train HT models, saving out results rows to csv, file_collect_results, defined below.

final_selected_train = True # after doing hyptuning (above) and selecting best model (see /home/csutter/DRIVE-clean/CNN/scripts/model_selection.ipynb), train the final selected model and save out the models and their predictions for all 30 folds. 
# final is running a one-off model, so set model specifics below
final_cnn = "A_resnet_TRLETrue_ASTTrue_L20_1_DR0_2_E75_AugTrue"
final_downstream_alg = "rf" # ex: "logistic", "gnb", "svm", "DNN", "rf"
final_downstream_hyp = {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True}

dir_of_datacsvs_CNNCalibPreds = "/home/csutter/DRIVE-clean/calibration/calib_CNN_data"

# load in weather data
hrrr_data_csv = "/home/csutter/DRIVE/weather_img_concatmodels/cnn_hrrr_fcsthr2/nestedcv_imgname_hrrrdata_fcsthr2.csv"

file_collect_results = "/home/csutter/DRIVE-clean/downstream/data_results/results_by_each_run_innerVal.csv"

# to save prediction data
predictions_directory = "/home/csutter/DRIVE-clean/downstream/data_preds" 
model_directory = "/home/csutter/DRIVE-clean/downstream/data_models_downstream" 
scalarmodel_directory = "/home/csutter/DRIVE-clean/downstream/data_models_scalar"

# algs_and_hyps_dict = {"DNN":"/home/csutter/DRIVE/dot/models_concatdata/nowcast/features12a/sitesplit/hypgrid_dnn.csv", "logistic": logistic_HT, "svm": svm_HT,"gnb": gnb_HT, "rf": "/home/csutter/DRIVE/dot/models_streamline/HT/hypgrid_rf_11feat_grid288.csv"}

cols_from_cnn = [
                "innerPhase",
                "outerPhase",
                "img_name",
                "img_orig",
                "site",
                "img_cat",
                "foldnum",
                "timeofday",
                "timeofevent",
                "calib_prob_dry",
                "calib_prob_poor_viz",
                "calib_prob_snow",
                "calib_prob_snow_severe",
                "calib_prob_wet",
                "calib_prob",
            ]

features_for_training = [
        "t2m",  # X
        "r2",  # X
        "uavg",  # added 1/4 calculated above
        "asnow",  # X
        "tp",  # X
        "tcc",  # 5/10
        # "dswrf", #5/10,
        # "dlwrf", #5/10,
        # "orog", #5/10,
        # "mslma", #5/10,
        # "si10", #5/10,
        # "sh2", #5/10,
        # "d2m", #5/10,
        # HERE!! Depending on which cols to use calib or not
        # "prob_dry",
        # "prob_poor_viz",
        # "prob_snow",
        # "prob_snow_severe",
        # "prob_wet",
        "calib_prob_dry",
        "calib_prob_poor_viz",
        "calib_prob_snow",
        "calib_prob_snow_severe",
        "calib_prob_wet"
    ]


logistic_HT = [
            {"max_iter": max_iter, "C": C}
            for max_iter in [100, 300, 500]
            for C in [0.01, 0.1, 1.0, 10.0, 100.0]
        ]

gnb_HT = [
            {"var_smoothing": 1e-12},
            {"var_smoothing": 1e-11},
            {"var_smoothing": 1e-10},
            {"var_smoothing": 1e-10},
            {"var_smoothing": 1e-8},
            {"var_smoothing": 1e-7},
            {"var_smoothing": 1e-6},
        ]

svm_HT = [
            {"kernel": "rbf", "C": 1, "gamma": "scale"},
            {"kernel": "rbf", "C": 1, "gamma": 1e-5},
            {"kernel": "rbf", "C": 1, "gamma": 1e-4},
            {"kernel": "rbf", "C": 1, "gamma": 1e-3},
            {"kernel": "rbf", "C": 1, "gamma": 1e-2},
            {"kernel": "rbf", "C": 1, "gamma": 0.1},
            {"kernel": "rbf", "C": 1, "gamma": 1},
            {"kernel": "rbf", "C": 1, "gamma": 10},
            {"kernel": "rbf", "C": 0.1, "gamma": "scale"},
            {"kernel": "rbf", "C": 0.1, "gamma": 1e-5},
            {"kernel": "rbf", "C": 0.1, "gamma": 1e-4},
            {"kernel": "rbf", "C": 0.1, "gamma": 1e-3},
            {"kernel": "rbf", "C": 0.1, "gamma": 1e-2},
            {"kernel": "rbf", "C": 0.1, "gamma": 0.1},
            {"kernel": "rbf", "C": 0.1, "gamma": 1},
            {"kernel": "rbf", "C": 0.1, "gamma": 10},
            {"kernel": "rbf", "C": 1e-2, "gamma": "scale"},
            {"kernel": "rbf", "C": 1e-2, "gamma": 1e-5},
            {"kernel": "rbf", "C": 1e-2, "gamma": 1e-4},
            {"kernel": "rbf", "C": 1e-2, "gamma": 1e-3},
            {"kernel": "rbf", "C": 1e-2, "gamma": 1e-2},
            {"kernel": "rbf", "C": 1e-2, "gamma": 0.1},
            {"kernel": "rbf", "C": 1e-2, "gamma": 1},
            {"kernel": "rbf", "C": 1e-2, "gamma": 10},
            {"kernel": "rbf", "C": 1e-3, "gamma": "scale"},
            {"kernel": "rbf", "C": 1e-3, "gamma": 1e-5},
            {"kernel": "rbf", "C": 1e-3, "gamma": 1e-4},
            {"kernel": "rbf", "C": 1e-3, "gamma": 1e-3},
            {"kernel": "rbf", "C": 1e-3, "gamma": 1e-2},
            {"kernel": "rbf", "C": 1e-3, "gamma": 0.1},
            {"kernel": "rbf", "C": 1e-3, "gamma": 1},
            {"kernel": "rbf", "C": 1e-3, "gamma": 10},
            {"kernel": "rbf", "C": 10, "gamma": "scale"},
            {"kernel": "rbf", "C": 10, "gamma": 1e-5},
            {"kernel": "rbf", "C": 10, "gamma": 1e-4},
            {"kernel": "rbf", "C": 10, "gamma": 1e-3},
            {"kernel": "rbf", "C": 10, "gamma": 1e-2},
            {"kernel": "rbf", "C": 10, "gamma": 0.1},
            {"kernel": "rbf", "C": 10, "gamma": 1},
            {"kernel": "rbf", "C": 10, "gamma": 10},
            {"kernel": "rbf", "C": 100, "gamma": "scale"},
            {"kernel": "rbf", "C": 100, "gamma": 1e-5},
            {"kernel": "rbf", "C": 100, "gamma": 1e-4},
            {"kernel": "rbf", "C": 100, "gamma": 1e-3},
            {"kernel": "rbf", "C": 100, "gamma": 1e-2},
            {"kernel": "rbf", "C": 100, "gamma": 0.1},
            {"kernel": "rbf", "C": 100, "gamma": 1},
            {"kernel": "rbf", "C": 100, "gamma": 10},
        ]

dnn_HT = [
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.0},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.0},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.0},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.0},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.0},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.001},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.001},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.001},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.001},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.001},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.01},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.01},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.01},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.01},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.01},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.1},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.1},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.1},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.1},
    {'hidden_layers': 5, 'hidden_units': '[256, 128, 64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.1},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.0},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.0},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.0},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.0},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.0},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.001},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.001},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.001},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.001},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.001},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.01},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.01},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.01},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.01},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.01},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.1},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.1},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.1},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.1},
    {'hidden_layers': 4, 'hidden_units': '[128, 64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.1},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.0},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.0},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.0},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.0},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.0},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.001},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.001},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.001},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.001},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.001},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.01},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.01},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.01},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.01},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.01},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.0, 'l2_reg': 0.1},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.2, 'l2_reg': 0.1},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.4, 'l2_reg': 0.1},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.6, 'l2_reg': 0.1},
    {'hidden_layers': 3, 'hidden_units': '[64, 32, 16]', 'dropout': 0.8, 'l2_reg': 0.1},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.0, 'l2_reg': 0.0},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.2, 'l2_reg': 0.0},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.4, 'l2_reg': 0.0},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.6, 'l2_reg': 0.0},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.8, 'l2_reg': 0.0},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.0, 'l2_reg': 0.001},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.2, 'l2_reg': 0.001},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.4, 'l2_reg': 0.001},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.6, 'l2_reg': 0.001},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.8, 'l2_reg': 0.001},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.0, 'l2_reg': 0.01},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.2, 'l2_reg': 0.01},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.4, 'l2_reg': 0.01},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.6, 'l2_reg': 0.01},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.8, 'l2_reg': 0.01},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.0, 'l2_reg': 0.1},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.2, 'l2_reg': 0.1},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.4, 'l2_reg': 0.1},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.6, 'l2_reg': 0.1},
    {'hidden_layers': 2, 'hidden_units': '[32, 16]', 'dropout': 0.8, 'l2_reg': 0.1},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.0, 'l2_reg': 0.0},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.2, 'l2_reg': 0.0},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.4, 'l2_reg': 0.0},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.6, 'l2_reg': 0.0},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.8, 'l2_reg': 0.0},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.0, 'l2_reg': 0.001},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.2, 'l2_reg': 0.001},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.4, 'l2_reg': 0.001},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.6, 'l2_reg': 0.001},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.8, 'l2_reg': 0.001},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.0, 'l2_reg': 0.01},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.2, 'l2_reg': 0.01},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.4, 'l2_reg': 0.01},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.6, 'l2_reg': 0.01},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.8, 'l2_reg': 0.01},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.0, 'l2_reg': 0.1},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.2, 'l2_reg': 0.1},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.4, 'l2_reg': 0.1},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.6, 'l2_reg': 0.1},
    {'hidden_layers': 1, 'hidden_units': '[16]', 'dropout': 0.8, 'l2_reg': 0.1},
]

rf_HT = [
    {'max_depth': 5, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 25, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 25, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 25, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 100, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 100, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 100, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 5, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 5, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 5, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 10, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 10, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 10, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_depth': 20, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_depth': 20, 'max_samples': 0.5, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 0.75, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_depth': 20, 'max_samples': 1.0, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 1, 'bootstrap': True},
    {'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 300, 'max_features': 3, 'min_samples_leaf': 5, 'bootstrap': True},
    {'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 1, 'bootstrap': True},
    {'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 300, 'max_features': 6, 'min_samples_leaf': 5, 'bootstrap': True},
    {'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 1, 'bootstrap': True},
    {'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': False},
    {'max_samples': 0.5, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 0.75, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
    {'max_samples': 1.0, 'n_estimators': 300, 'max_features': 11, 'min_samples_leaf': 5, 'bootstrap': True},
]